export const SET_ROUND = 'SET_ROUND'
export const ADD_ROUND = 'ADD_ROUND'
export const REMOVE_ROUND = 'REMOVE_ROUND'
export const SET_BREATH_COUNT = 'SET_BREATH_COUNT'
export const SET_ROUND_TIME = 'SET_ROUND_TIME'
